### ISSUE TITLE
Off subject? Combining Cyfrin and Chainlink projects?

### ISSUE THREAD

**Issue by whatTHEh3ll** [Cyfrin/foundry-nft-f23#17]
I'm trying to create an on chain nft with Foundry. I'm basing my project on the Cyfrin NFT  repo. 

Except that I'm not doing the Moodnft. I decided to go with a Smart contract from another Patrick Collins project. Here https://github.com/PatrickAlphaC/all-on-chain-generated-nft.

I would like to create a basic on chain svg with foundry. The contract seems to compile correctly. However when I execute a test I get an error on the 'testTokenURIIsCorrect()' function. Here's the test --https://gitlab.com/b2896/foundry-nft/-/blob/main/test/SvgNftTwoTest.t.sol

My project repo https://gitlab.com/b2896/foundry-nft/

Any ideas on writing a successful unit test?

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. For your custom project, the community might not have time to help triage since it's outside the course materials. 

However, could you please:
1. Make this a discussion on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Join the Cyfrin discord to chat with other devs: https://discord.gg/cyfrin

Thank you!
